<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Relying Party Resiliency Platform</title>
    <meta name="description" content="Inspecting the behaviour of Relying Party software in extreme corner-cases">
    <meta name="author" content="Koen van Hove">

    <style>
        .content {
            max-width: 1024px;
            margin: auto;
        }
    </style>
</head>
<body>
<div class="content">
    <h1>Relying Party Resiliency Platform</h1>
    <p>
        In order to request access, please send an email to k.w.vanhove@student.utwente.nl containing your name,
        affiliation, and what you aim to do with your access to the testbed. Please note that the approval process is
        done manually by me, so it might take some time. No guarantees about the stability or availability of the testbed are made.
    </p>
    <p>
        Kind regards,<br>
        Koen van Hove
    </p>
    <p>
        <a href="mailto:k.w.vanhove@student.utwente.nl?subject=Relying Party Resiliency Platform access request">Request access</a>
    </p>
</div>
</body>
</html>
